name: Main

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # Windows
  windowsBuild:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Installing Libraries
        run: |
          haxe -cp ./actions -D analyzer-optimize -main Main --interp

      - name: Building
        run: haxelib run lime build windows -final

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export/release/windows/bin
          if-no-files-found: error

  # Linux
  linuxBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Installing Libraries
        run: |
          haxe -cp ./actions -D analyzer-optimize -main Main --interp

      - name: Building
        run: haxelib run lime build linux -final

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: linuxBuild
          path: export/release/linux/bin
          if-no-files-found: error

  # Mac
  macBuild:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Installing Libraries
        run: |
          haxe -cp ./actions -D analyzer-optimize -main Main --interp

      - name: Building
        run: haxelib run lime build mac -final

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: macBuild
          path: export/release/macos/bin
          if-no-files-found: error
